print(1 + 2 * 3);
print((1 + 2) * 3);
print(10 % 3);
print(7 / 2);
print(-5 + 3);
print(2 < 3);
print(3 <= 3);
print("a" + "b" + "c");
print(1 + "x");
print(true && false);
print(true || false);
print(false || "fallback");
print(1 === 1);
print(1 === "1");
print(1 == "1");
print(null == undefined);
print(!0);
print(2 > 1 ? "yes" : "no");
print(NaN === NaN);
print(10 - 4 - 3);
